source "https://rubygems.org"

gem "minitest", "~> 5.0"
gem 'pry'
gem "rake", "~> 12.0"
gem 'rack_csrf'
gem 'rest-client'
gem 'require_all'
# rack_csrf mentions known version compatibility; if it gets weird, try:
# gem 'sinatra', '>= 0.9.4', '<= 1.4.4'
gem 'sinatra', '2.0.8.1'
gem 'sinatra-contrib'
gem 'thin'
